source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘8.0’
use_frameworks!

pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'pop'
pod 'Toast'

target ’ESLibraryFramework’ do
pod 'AFNetworking'
pod 'ReactiveObjC'
pod 'MJRefresh'
end
